DROP DATABASE IF EXISTS ServiceHub;
CREATE DATABASE ServiceHub;
\c ServiceHub;

CREATE TABLE Users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE Posts (
    id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT,
    user_id INTEGER REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Comments (
    id SERIAL PRIMARY KEY,
    contents TEXT NOT NULL,
    post_id INTEGER REFERENCES Posts(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES Users(id) ON DELETE SET NULL
);
